//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IPT_WebAPI.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class IPT_DATABASEEntities1 : DbContext
    {
        public IPT_DATABASEEntities1()
            : base("name=IPT_DATABASEEntities1")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public DbSet<CATOGARY_MAST> CATOGARY_MAST { get; set; }
        public DbSet<IT_EXPERT_MAST> IT_EXPERT_MAST { get; set; }
        public DbSet<MESSAGE_MASTER> MESSAGE_MASTER { get; set; }
        public DbSet<STUDENT_DETAILS> STUDENT_DETAILS { get; set; }
        public DbSet<STUDENT_MAST> STUDENT_MAST { get; set; }
        public DbSet<SYSTEM_USER> SYSTEM_USER { get; set; }
    }
}
