//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IPT_WebAPI.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class MESSAGE_MASTER
    {
        public string STUDENT_ID { get; set; }
        public string IT_EXPERT_USERNAME { get; set; }
        public string MESSAGE_BODY_STD { get; set; }
        public int AUTO_NUM { get; set; }
        public string MESSAGE_BODY_ITE { get; set; }
    }
}
