//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IPT_WebAPI.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class SYSTEM_USER
    {
        public string SU_USER_ID { get; set; }
        public string SU_USERNAME { get; set; }
        public string SU_PASSWORD { get; set; }
        public string SU_NAME { get; set; }
        public string USER_TYPE { get; set; }
        public int AUTO_NUM { get; set; }
    }
}
